name: Test Project
on: [push, workflow_dispatch]

jobs:
  test-wf:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dps
        run: npm ci
      - name: Run test
        run: npm test
  deploy-wf:
    needs: test-wf
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dps
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
